# PART 2
## Adding, removing, and sorting elemrnts
  The section covers

    `np.sort()`

    `np.concatenate()`

Sorting an element is simple with `np.sort()`. You can specify the axis,kind,and order when call the function.

if you start with this array:

In [ ]:
import numpy as np
arr = np.array([2,1,5,3,7,4,6,8])

You can quickly sort the numbers in ascending order with :

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use :



*   **argsort**  , which's an idirect sort along a specified axis
*   **lexsort**  , which's an idirect stable sort on multiple keys
*   **searchsorted** , which will find elements in a sorted array 
*  **partition**  , which's a partical sort



If you started with this arrays:

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

You can concatenate them with `np.concatenate`



In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

Or, if you started with these arrays:

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
# You can concatenate them (x,y) with:

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# NumPy.concatenate

    numpy.concatenate((a1,a2,...), axis = 0, out=None , dtype=None, casting="same_kind")


join a sequence of arrays along an existing axis

---

**Parameters**  :  

1.   **a1,a2, ...** : *sequence of array_like*
  
  The arrays must have the same shape, except in the dimension corresponding to axis(The first by default)
2.  **axis** : *int, Optional*

  The axis  along which the arrays will be joined, if axis is None, arrays are flattened before use. Default is 0.

3.   **out** : *nadarray, optimal* 

  if provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified

4.   **dtype** :  *str or dtype*

  if provided, the destination array will have this dtype. Cannot be provided together with out.
  
  *New in version  1.20.0.*

5.  **casting** : *{'no','equiv','safe','same_kind','unsafe'},optimal*

  Controls what kind of data casting may occur, Defaults to 
  
  'same_kind'.

  *New in version 1.20.0*
---

**Returns**   :   
*  **res**: *nadarray*

  The concatenated array.

## Examples

1 --

In [ ]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

This function will not preserve masking of MaskedArray inputs

In [ ]:
a = np.ma.arange(3)
a[1] = np.ma.masked
b = np.arange(2, 5)
a

masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)

In [ ]:
b

array([2, 3, 4])

In [ ]:
np.concatenate([a, b])

masked_array(data=[0, 1, 2, 2, 3, 4],
             mask=False,
       fill_value=999999)

In [ ]:
np.ma.concatenate([a, b])

masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)