# PART 3
## How do you know the shape and size of an array?
## Can you reshape an array?

  The section covers

```
 * ndarray.ndim
 * Ndarray.size
 * ndarray.shape
 * arr.reshape

```





`ndarray.ndim` ---- will tell you number of axes, or demensions of the array

`ndarray.size` ---- will tell you the total number of elements of the array.This is the product of the elements of array's shape. 


`ndarray` ---- will display a tuple of integers that indicate the number of elements stored along each dimension of the array. if, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is `(2, 3)`


**Example** :

In [ ]:
import numpy as np

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])

To find the number of dimensions of the array, run :

In [ ]:
array_example.ndim

3

To find the total number of elements in the array, run:

In [ ]:
array_example.size

24

And to find the shape of your array, run:

In [ ]:
array_example.shape

(3, 2, 4)

# Can you reshape an array ?

This section covers `arr,reshape()`

**YES !**


Using `arr.reshape()`  will give a new shape to an array without changing the data.just remeber that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. if you start with an array with 12 elements, you'll need to make sure that your new array also has a total of 12 elements 


if you start with this array : 

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


You cane use `reshape()` to reshape your array.For example, you can reshape this array to an array with three rows and two columns:

In [ ]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


With `np.reshape`, you can specify a few optional parameters :

In [ ]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

`a` is the array to be reshape 

---

`newshape` is the new shape you want.You can specify or a tuple of integers. if you sepcify an integer , the result will be an array of that length. The shape should be compatible with the orignal shape.

---

`order : C` mean to read/write the elements using C-like index order, `F` means to read/write the elements using Fortran-like index order, `A` means to read/write the elements in Fortran-like order if a is Fortran contiguous in memory, C-like order otherwise(This's an optimal parameter and doesn't need to be specified)


